// ============================================================================
// Mock 키워드 변형 및 후보 데이터
// ============================================================================

import type { KeywordVariant, KeywordCandidate } from '@/types/domain'

export const mockKeywordVariants: KeywordVariant[] = [
  // 사설토토 (kw-002) 변형
  { id: 'kv-001', keywordId: 'kw-002', variantText: 'ㅅㅅㅌㅌ', variantType: 'CHOSUNG', isAutoGenerated: true, detectionCount: 45, createdAt: new Date(2025, 10, 1) },
  { id: 'kv-002', keywordId: 'kw-002', variantText: '사설토1토', variantType: 'TYPO', isAutoGenerated: true, detectionCount: 23, createdAt: new Date(2025, 10, 2) },
  { id: 'kv-003', keywordId: 'kw-002', variantText: 'saseltoto', variantType: 'MIXED_LANG', isAutoGenerated: true, detectionCount: 12, createdAt: new Date(2025, 10, 3) },
  { id: 'kv-004', keywordId: 'kw-002', variantText: '사ㅅ설토토', variantType: 'CHAR_REPLACE', isAutoGenerated: true, detectionCount: 18, createdAt: new Date(2025, 10, 4) },
  { id: 'kv-005', keywordId: 'kw-002', variantText: '사설 토토', variantType: 'MORPHEME', isAutoGenerated: false, detectionCount: 67, createdAt: new Date(2025, 10, 5) },

  // 불법토토 (kw-001) 변형
  { id: 'kv-006', keywordId: 'kw-001', variantText: 'ㅂㅂㅌㅌ', variantType: 'CHOSUNG', isAutoGenerated: true, detectionCount: 34, createdAt: new Date(2025, 10, 6) },
  { id: 'kv-007', keywordId: 'kw-001', variantText: '불법토1토', variantType: 'TYPO', isAutoGenerated: true, detectionCount: 19, createdAt: new Date(2025, 10, 7) },
  { id: 'kv-008', keywordId: 'kw-001', variantText: '불.법.토.토', variantType: 'CHAR_REPLACE', isAutoGenerated: true, detectionCount: 28, createdAt: new Date(2025, 10, 8) },
  { id: 'kv-009', keywordId: 'kw-001', variantText: '불법 토토', variantType: 'MORPHEME', isAutoGenerated: false, detectionCount: 52, createdAt: new Date(2025, 10, 9) },

  // 온라인카지노 (kw-016) 변형
  { id: 'kv-010', keywordId: 'kw-016', variantText: 'ㅇㄹㅇㅋㅈㄴ', variantType: 'CHOSUNG', isAutoGenerated: true, detectionCount: 56, createdAt: new Date(2025, 10, 10) },
  { id: 'kv-011', keywordId: 'kw-016', variantText: '온라인카지노추천', variantType: 'MORPHEME', isAutoGenerated: true, detectionCount: 89, createdAt: new Date(2025, 10, 11) },
  { id: 'kv-012', keywordId: 'kw-016', variantText: '온라인카ㅈ노', variantType: 'CHAR_REPLACE', isAutoGenerated: true, detectionCount: 15, createdAt: new Date(2025, 10, 12) },
  { id: 'kv-013', keywordId: 'kw-016', variantText: 'onlinecasino', variantType: 'MIXED_LANG', isAutoGenerated: true, detectionCount: 34, createdAt: new Date(2025, 10, 13) },

  // 먹튀검증 (kw-009) 변형
  { id: 'kv-014', keywordId: 'kw-009', variantText: 'ㅁㅌㄱㅈ', variantType: 'CHOSUNG', isAutoGenerated: true, detectionCount: 41, createdAt: new Date(2025, 10, 14) },
  { id: 'kv-015', keywordId: 'kw-009', variantText: '먹.튀.검.증', variantType: 'CHAR_REPLACE', isAutoGenerated: true, detectionCount: 22, createdAt: new Date(2025, 10, 15) },
  { id: 'kv-016', keywordId: 'kw-009', variantText: '먹튀 검증', variantType: 'MORPHEME', isAutoGenerated: false, detectionCount: 78, createdAt: new Date(2025, 10, 16) },

  // 바카라 (kw-017) 변형
  { id: 'kv-017', keywordId: 'kw-017', variantText: 'ㅂㅋㄹ', variantType: 'CHOSUNG', isAutoGenerated: true, detectionCount: 29, createdAt: new Date(2025, 10, 17) },
  { id: 'kv-018', keywordId: 'kw-017', variantText: 'baccarat', variantType: 'MIXED_LANG', isAutoGenerated: true, detectionCount: 45, createdAt: new Date(2025, 10, 18) },
  { id: 'kv-019', keywordId: 'kw-017', variantText: '바카1라', variantType: 'TYPO', isAutoGenerated: true, detectionCount: 11, createdAt: new Date(2025, 10, 19) },

  // 파워볼 (kw-042) 변형
  { id: 'kv-020', keywordId: 'kw-042', variantText: 'ㅍㅇㅂ', variantType: 'CHOSUNG', isAutoGenerated: true, detectionCount: 38, createdAt: new Date(2025, 10, 20) },
  { id: 'kv-021', keywordId: 'kw-042', variantText: 'powerball', variantType: 'MIXED_LANG', isAutoGenerated: true, detectionCount: 52, createdAt: new Date(2025, 10, 21) },
  { id: 'kv-022', keywordId: 'kw-042', variantText: '파워 볼', variantType: 'MORPHEME', isAutoGenerated: false, detectionCount: 44, createdAt: new Date(2025, 10, 22) },

  // 안전놀이터 (kw-003) 변형
  { id: 'kv-023', keywordId: 'kw-003', variantText: 'ㅇㅈㄴㅇㅌ', variantType: 'CHOSUNG', isAutoGenerated: true, detectionCount: 33, createdAt: new Date(2025, 10, 23) },
  { id: 'kv-024', keywordId: 'kw-003', variantText: '안전 놀이터', variantType: 'MORPHEME', isAutoGenerated: false, detectionCount: 61, createdAt: new Date(2025, 10, 24) },
  { id: 'kv-025', keywordId: 'kw-003', variantText: '안전놀이터추천', variantType: 'MORPHEME', isAutoGenerated: true, detectionCount: 47, createdAt: new Date(2025, 10, 25) },
]

export const mockKeywordCandidates: KeywordCandidate[] = [
  {
    id: 'kc-001',
    keyword: '벳365',
    suggestedLayer: 'DIRECT',
    suggestedCategory: '스포츠베팅',
    source: 'AI_SUGGESTION',
    sourceDetail: { model: 'gpt-4o', confidence: 0.92 },
    status: 'PENDING',
    similarKeywordIds: ['kw-001', 'kw-002'],
    reviewedById: null,
    reviewedAt: null,
    approvedKeywordId: null,
    createdAt: new Date(2026, 2, 10),
  },
  {
    id: 'kc-002',
    keyword: '무료충전',
    suggestedLayer: 'BAIT',
    suggestedCategory: '카지노',
    source: 'META_EXTRACTED',
    sourceDetail: { siteId: 'site-045', tag: 'meta-keywords' },
    status: 'PENDING',
    similarKeywordIds: ['kw-026'],
    reviewedById: null,
    reviewedAt: null,
    approvedKeywordId: null,
    createdAt: new Date(2026, 2, 11),
  },
  {
    id: 'kc-003',
    keyword: '가입머니',
    suggestedLayer: 'BAIT',
    suggestedCategory: '스포츠베팅',
    source: 'AI_SUGGESTION',
    sourceDetail: { model: 'gpt-4o', confidence: 0.88 },
    status: 'PENDING',
    similarKeywordIds: ['kw-011'],
    reviewedById: null,
    reviewedAt: null,
    approvedKeywordId: null,
    createdAt: new Date(2026, 2, 12),
  },
  {
    id: 'kc-004',
    keyword: '꽁머니',
    suggestedLayer: 'BAIT',
    suggestedCategory: '스포츠베팅',
    source: 'COMMUNITY_MENTION',
    sourceDetail: { forum: 'mlbpark', threadCount: 23 },
    status: 'APPROVED',
    similarKeywordIds: ['kw-003'],
    reviewedById: 'user-001',
    reviewedAt: new Date(2026, 2, 13),
    approvedKeywordId: 'kw-051',
    createdAt: new Date(2026, 2, 9),
  },
  {
    id: 'kc-005',
    keyword: '놀이터추천',
    suggestedLayer: 'VERIFICATION',
    suggestedCategory: '스포츠베팅',
    source: 'AI_SUGGESTION',
    sourceDetail: { model: 'gpt-4o', confidence: 0.85 },
    status: 'PENDING',
    similarKeywordIds: ['kw-003', 'kw-011'],
    reviewedById: null,
    reviewedAt: null,
    approvedKeywordId: null,
    createdAt: new Date(2026, 2, 14),
  },
  {
    id: 'kc-006',
    keyword: '실시간중계',
    suggestedLayer: 'COMMUNITY',
    suggestedCategory: '경마',
    source: 'META_EXTRACTED',
    sourceDetail: { siteId: 'site-102', tag: 'title' },
    status: 'REJECTED',
    similarKeywordIds: ['kw-039'],
    reviewedById: 'user-002',
    reviewedAt: new Date(2026, 2, 12),
    approvedKeywordId: null,
    createdAt: new Date(2026, 2, 8),
  },
  {
    id: 'kc-007',
    keyword: '고액배팅',
    suggestedLayer: 'DIRECT',
    suggestedCategory: '카지노',
    source: 'AI_SUGGESTION',
    sourceDetail: { model: 'gpt-4o', confidence: 0.91 },
    status: 'PENDING',
    similarKeywordIds: ['kw-016', 'kw-017'],
    reviewedById: null,
    reviewedAt: null,
    approvedKeywordId: null,
    createdAt: new Date(2026, 2, 15),
  },
]
