"""initial tables

Revision ID: ead60ea1b22c
Revises: 
Create Date: 2026-03-18 23:46:04.196139

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ead60ea1b22c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('domain_clusters',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('sites',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'INACTIVE', 'CLOSED', 'MONITORING', name='sitestatus'), nullable=False),
    sa.Column('category', sa.Enum('SPORTS_BETTING', 'HORSE_RACING', 'CASINO', 'OTHER_GAMBLING', 'NON_GAMBLING', name='sitecategory'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('first_detected_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('tags', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('whois_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('dns_records', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('login_required', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('url')
    )
    op.create_index('ix_sites_category', 'sites', ['category'], unique=False)
    op.create_index('ix_sites_domain', 'sites', ['domain'], unique=False)
    op.create_index('ix_sites_status', 'sites', ['status'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=True),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('email_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('password_hash', sa.Text(), nullable=True),
    sa.Column('image', sa.Text(), nullable=True),
    sa.Column('role', sa.Enum('SUPER_ADMIN', 'ADMIN', 'OPERATOR', 'INVESTIGATOR', 'LEGAL', name='userrole'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    op.create_index('ix_users_email', 'users', ['email'], unique=False)
    op.create_index('ix_users_role', 'users', ['role'], unique=False)
    op.create_table('verification_tokens',
    sa.Column('identifier', sa.String(length=255), nullable=False),
    sa.Column('token', sa.String(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('identifier', 'token')
    )
    op.create_index('ix_verification_tokens_token', 'verification_tokens', ['token'], unique=False)
    op.create_table('accounts',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('provider', sa.String(length=50), nullable=False),
    sa.Column('provider_account_id', sa.String(length=255), nullable=False),
    sa.Column('refresh_token', sa.Text(), nullable=True),
    sa.Column('access_token', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.Integer(), nullable=True),
    sa.Column('token_type', sa.String(length=50), nullable=True),
    sa.Column('scope', sa.Text(), nullable=True),
    sa.Column('id_token', sa.Text(), nullable=True),
    sa.Column('session_state', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_accounts_provider_provider_account_id', 'accounts', ['provider', 'provider_account_id'], unique=True)
    op.create_index('ix_accounts_user_id', 'accounts', ['user_id'], unique=False)
    op.create_table('audit_logs',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.String(length=36), nullable=False),
    sa.Column('action', sa.Enum('CREATE', 'READ', 'UPDATE', 'DELETE', 'DOWNLOAD', 'VERIFY', 'EXPORT', name='auditaction'), nullable=False),
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_ip', sa.String(length=45), nullable=True),
    sa.Column('details', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('prev_hash', sa.String(length=64), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_audit_logs_action', 'audit_logs', ['action'], unique=False)
    op.create_index('ix_audit_logs_actor_id', 'audit_logs', ['actor_id'], unique=False)
    op.create_index('ix_audit_logs_created_at', 'audit_logs', ['created_at'], unique=False)
    op.create_index('ix_audit_logs_entity_type_entity_id', 'audit_logs', ['entity_type', 'entity_id'], unique=False)
    op.create_table('classification_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('model', sa.Enum('CLAUDE_HAIKU', 'XGBOOST', 'BERT', 'ENSEMBLE', name='classificationmodel'), nullable=False),
    sa.Column('category', sa.Enum('SPORTS_BETTING', 'HORSE_RACING', 'CASINO', 'OTHER_GAMBLING', 'NON_GAMBLING', name='sitecategory'), nullable=True),
    sa.Column('confidence_score', sa.Float(), nullable=True),
    sa.Column('evidence', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('review_status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'MODIFIED', name='reviewstatus'), nullable=False),
    sa.Column('reviewed_by_id', sa.String(length=36), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_classification_results_model', 'classification_results', ['model'], unique=False)
    op.create_index('ix_classification_results_review_status', 'classification_results', ['review_status'], unique=False)
    op.create_index('ix_classification_results_site_id', 'classification_results', ['site_id'], unique=False)
    op.create_table('domain_histories',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('domain', sa.String(length=255), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('dns_records', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.Enum('ALIVE', 'DEAD', 'REDIRECT', name='domainstatus'), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('response_time_ms', sa.Integer(), nullable=True),
    sa.Column('redirect_url', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_domain_histories_domain', 'domain_histories', ['domain'], unique=False)
    op.create_index('ix_domain_histories_site_id', 'domain_histories', ['site_id'], unique=False)
    op.create_index('ix_domain_histories_status', 'domain_histories', ['status'], unique=False)
    op.create_table('investigations',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('status', sa.Enum('QUEUED', 'IN_PROGRESS', 'STAGE_1_COMPLETE', 'STAGE_2_COMPLETE', 'STAGE_3_COMPLETE', 'COMPLETED', 'FAILED', 'CANCELLED', name='investigationstatus'), nullable=False),
    sa.Column('current_stage', sa.Integer(), nullable=True),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('proxy_used', sa.String(length=255), nullable=True),
    sa.Column('browser_fingerprint', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('batch_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_investigations_batch_id', 'investigations', ['batch_id'], unique=False)
    op.create_index('ix_investigations_created_by_id', 'investigations', ['created_by_id'], unique=False)
    op.create_index('ix_investigations_site_id', 'investigations', ['site_id'], unique=False)
    op.create_index('ix_investigations_status', 'investigations', ['status'], unique=False)
    op.create_table('keywords',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('keyword', sa.String(length=255), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('detection_count', sa.Integer(), nullable=False),
    sa.Column('created_by_id', sa.String(length=36), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('keyword')
    )
    op.create_index('ix_keywords_is_active', 'keywords', ['is_active'], unique=False)
    op.create_index('ix_keywords_keyword', 'keywords', ['keyword'], unique=False)
    op.create_table('popup_patterns',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=True),
    sa.Column('pattern_type', sa.String(length=100), nullable=False),
    sa.Column('css_selector', sa.Text(), nullable=True),
    sa.Column('close_button_selector', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('success_count', sa.Integer(), nullable=False),
    sa.Column('fail_count', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_popup_patterns_pattern_type', 'popup_patterns', ['pattern_type'], unique=False)
    op.create_index('ix_popup_patterns_site_id', 'popup_patterns', ['site_id'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('session_token', sa.String(length=255), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('session_token')
    )
    op.create_index('ix_sessions_session_token', 'sessions', ['session_token'], unique=False)
    op.create_index('ix_sessions_user_id', 'sessions', ['user_id'], unique=False)
    op.create_table('site_domain_clusters',
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('cluster_id', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['cluster_id'], ['domain_clusters.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('site_id', 'cluster_id')
    )
    op.create_index('ix_site_domain_clusters_cluster_id', 'site_domain_clusters', ['cluster_id'], unique=False)
    op.create_index('ix_site_domain_clusters_site_id', 'site_domain_clusters', ['site_id'], unique=False)
    op.create_table('system_settings',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('key', sa.String(length=255), nullable=False),
    sa.Column('value', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('updated_by_id', sa.String(length=36), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['updated_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('key')
    )
    op.create_index('ix_system_settings_key', 'system_settings', ['key'], unique=False)
    op.create_table('detection_results',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('site_id', sa.String(length=36), nullable=False),
    sa.Column('source', sa.Enum('GOOGLE_SEARCH', 'CRAWLING', 'COMMUNITY', 'MANUAL', name='detectionsource'), nullable=False),
    sa.Column('keyword_id', sa.String(length=36), nullable=True),
    sa.Column('raw_data', postgresql.JSON(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['keyword_id'], ['keywords.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['site_id'], ['sites.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_detection_results_keyword_id', 'detection_results', ['keyword_id'], unique=False)
    op.create_index('ix_detection_results_site_id', 'detection_results', ['site_id'], unique=False)
    op.create_index('ix_detection_results_source', 'detection_results', ['source'], unique=False)
    op.create_table('evidence_files',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('file_type', sa.Enum('SCREENSHOT', 'HTML', 'WARC', 'NETWORK_LOG', 'WHOIS', 'METADATA', 'SINGLEFILE', name='evidencefiletype'), nullable=False),
    sa.Column('stage', sa.Integer(), nullable=False),
    sa.Column('file_path', sa.Text(), nullable=False),
    sa.Column('file_size', sa.BigInteger(), nullable=True),
    sa.Column('mime_type', sa.String(length=100), nullable=True),
    sa.Column('sha256_hash', sa.String(length=64), nullable=True),
    sa.Column('original_filename', sa.String(length=255), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_files_file_type', 'evidence_files', ['file_type'], unique=False)
    op.create_index('ix_evidence_files_investigation_id', 'evidence_files', ['investigation_id'], unique=False)
    op.create_index('ix_evidence_files_sha256_hash', 'evidence_files', ['sha256_hash'], unique=False)
    op.create_table('manual_intervention_queues',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('CAPTCHA', 'OTP', 'UNKNOWN_FORM', name='interventiontype'), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'IN_PROGRESS', 'RESOLVED', 'EXPIRED', name='interventionstatus'), nullable=False),
    sa.Column('cdp_session_url', sa.Text(), nullable=True),
    sa.Column('screenshot_path', sa.Text(), nullable=True),
    sa.Column('assigned_to_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('resolution_notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_to_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_manual_intervention_queues_assigned_to_id', 'manual_intervention_queues', ['assigned_to_id'], unique=False)
    op.create_index('ix_manual_intervention_queues_investigation_id', 'manual_intervention_queues', ['investigation_id'], unique=False)
    op.create_index('ix_manual_intervention_queues_status', 'manual_intervention_queues', ['status'], unique=False)
    op.create_table('sms_numbers',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('phone_number', sa.String(length=20), nullable=False),
    sa.Column('country_code', sa.String(length=5), nullable=False),
    sa.Column('provider', sa.Enum('PVAPINS', 'GRIZZLYSMS', 'SMS_ACTIVATE', 'MANUAL', name='smsprovider'), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'USED', 'EXPIRED', 'BLOCKED', name='smsnumberstatus'), nullable=False),
    sa.Column('investigation_id', sa.String(length=36), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('expired_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('cost_usd', sa.Numeric(precision=10, scale=4), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['investigation_id'], ['investigations.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sms_numbers_investigation_id', 'sms_numbers', ['investigation_id'], unique=False)
    op.create_index('ix_sms_numbers_phone_number', 'sms_numbers', ['phone_number'], unique=False)
    op.create_index('ix_sms_numbers_status', 'sms_numbers', ['status'], unique=False)
    op.create_table('evidence_timestamps',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_file_id', sa.String(length=36), nullable=False),
    sa.Column('type', sa.Enum('OPENTIMESTAMPS', 'RFC3161', name='timestamptype'), nullable=False),
    sa.Column('timestamp_value', sa.DateTime(timezone=True), nullable=False),
    sa.Column('proof_file_path', sa.Text(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VALID', 'INVALID', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evidence_timestamps_evidence_file_id', 'evidence_timestamps', ['evidence_file_id'], unique=False)
    op.create_table('hash_records',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('evidence_file_id', sa.String(length=36), nullable=False),
    sa.Column('algorithm', sa.Enum('SHA256', name='hashalgorithm'), nullable=False),
    sa.Column('hash_value', sa.String(length=128), nullable=False),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('verification_status', sa.Enum('PENDING', 'VALID', 'INVALID', name='verificationstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['evidence_file_id'], ['evidence_files.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_hash_records_evidence_file_id', 'hash_records', ['evidence_file_id'], unique=False)
    op.create_table('sms_messages',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('sms_number_id', sa.String(length=36), nullable=False),
    sa.Column('message_text', sa.Text(), nullable=True),
    sa.Column('otp_code', sa.String(length=20), nullable=True),
    sa.Column('received_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('parsed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['sms_number_id'], ['sms_numbers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_sms_messages_sms_number_id', 'sms_messages', ['sms_number_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_sms_messages_sms_number_id', table_name='sms_messages')
    op.drop_table('sms_messages')
    op.drop_index('ix_hash_records_evidence_file_id', table_name='hash_records')
    op.drop_table('hash_records')
    op.drop_index('ix_evidence_timestamps_evidence_file_id', table_name='evidence_timestamps')
    op.drop_table('evidence_timestamps')
    op.drop_index('ix_sms_numbers_status', table_name='sms_numbers')
    op.drop_index('ix_sms_numbers_phone_number', table_name='sms_numbers')
    op.drop_index('ix_sms_numbers_investigation_id', table_name='sms_numbers')
    op.drop_table('sms_numbers')
    op.drop_index('ix_manual_intervention_queues_status', table_name='manual_intervention_queues')
    op.drop_index('ix_manual_intervention_queues_investigation_id', table_name='manual_intervention_queues')
    op.drop_index('ix_manual_intervention_queues_assigned_to_id', table_name='manual_intervention_queues')
    op.drop_table('manual_intervention_queues')
    op.drop_index('ix_evidence_files_sha256_hash', table_name='evidence_files')
    op.drop_index('ix_evidence_files_investigation_id', table_name='evidence_files')
    op.drop_index('ix_evidence_files_file_type', table_name='evidence_files')
    op.drop_table('evidence_files')
    op.drop_index('ix_detection_results_source', table_name='detection_results')
    op.drop_index('ix_detection_results_site_id', table_name='detection_results')
    op.drop_index('ix_detection_results_keyword_id', table_name='detection_results')
    op.drop_table('detection_results')
    op.drop_index('ix_system_settings_key', table_name='system_settings')
    op.drop_table('system_settings')
    op.drop_index('ix_site_domain_clusters_site_id', table_name='site_domain_clusters')
    op.drop_index('ix_site_domain_clusters_cluster_id', table_name='site_domain_clusters')
    op.drop_table('site_domain_clusters')
    op.drop_index('ix_sessions_user_id', table_name='sessions')
    op.drop_index('ix_sessions_session_token', table_name='sessions')
    op.drop_table('sessions')
    op.drop_index('ix_popup_patterns_site_id', table_name='popup_patterns')
    op.drop_index('ix_popup_patterns_pattern_type', table_name='popup_patterns')
    op.drop_table('popup_patterns')
    op.drop_index('ix_keywords_keyword', table_name='keywords')
    op.drop_index('ix_keywords_is_active', table_name='keywords')
    op.drop_table('keywords')
    op.drop_index('ix_investigations_status', table_name='investigations')
    op.drop_index('ix_investigations_site_id', table_name='investigations')
    op.drop_index('ix_investigations_created_by_id', table_name='investigations')
    op.drop_index('ix_investigations_batch_id', table_name='investigations')
    op.drop_table('investigations')
    op.drop_index('ix_domain_histories_status', table_name='domain_histories')
    op.drop_index('ix_domain_histories_site_id', table_name='domain_histories')
    op.drop_index('ix_domain_histories_domain', table_name='domain_histories')
    op.drop_table('domain_histories')
    op.drop_index('ix_classification_results_site_id', table_name='classification_results')
    op.drop_index('ix_classification_results_review_status', table_name='classification_results')
    op.drop_index('ix_classification_results_model', table_name='classification_results')
    op.drop_table('classification_results')
    op.drop_index('ix_audit_logs_entity_type_entity_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_created_at', table_name='audit_logs')
    op.drop_index('ix_audit_logs_actor_id', table_name='audit_logs')
    op.drop_index('ix_audit_logs_action', table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index('ix_accounts_user_id', table_name='accounts')
    op.drop_index('ix_accounts_provider_provider_account_id', table_name='accounts')
    op.drop_table('accounts')
    op.drop_index('ix_verification_tokens_token', table_name='verification_tokens')
    op.drop_table('verification_tokens')
    op.drop_index('ix_users_role', table_name='users')
    op.drop_index('ix_users_email', table_name='users')
    op.drop_table('users')
    op.drop_index('ix_sites_status', table_name='sites')
    op.drop_index('ix_sites_domain', table_name='sites')
    op.drop_index('ix_sites_category', table_name='sites')
    op.drop_table('sites')
    op.drop_table('domain_clusters')
    # ### end Alembic commands ###
